version: '3.4'

services:
  server:
    platform: linux/x86_64
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/jun-hackathon-db
        SPRING_DATASOURCE_USERNAME: &db_username "postgres"
        SPRING_DATASOURCE_PASSWORD: &db_password "postgres"

    volumes:
      - ./keys:/app/keys

  database:
    image: postgres:16
    environment:
      POSTGRES_DB: jun-hackathon-db
      POSTGRES_USER: *db_username
      POSTGRES_PASSWORD: *db_password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: